# Generated by Django 2.2.6 on 2019-10-08 18:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('icecream', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='icecream',
            old_name='flavor_text',
            new_name='flavor',
        ),
        migrations.AddField(
            model_name='icecream',
            name='available',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('SEASONAL', 'Seasonal')], default='DAILY', max_length=255),
        ),
        migrations.AddField(
            model_name='icecream',
            name='base',
            field=models.CharField(choices=[('CHOCOLATE', 'Chocolate'), ('VANILLA', 'Vanilla')], default='CHOCOLATE', max_length=30),
        ),
        migrations.AddField(
            model_name='icecream',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='icecream',
            name='date_churned',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date churned'),
        ),
    ]
